call RunSimulation SimpleChatMessages
call RunSimulation GuessANumber
call RunSimulation ServerPerformance
call RunSimulation XmlMessages
call RunSimulation Protocols
rem call RunSimulation BreakingPoint
call RunSimulation HighLoad
call RunSimulation Federation
call RunSimulation ContentType
call RunSimulation Distributions
call RunSimulation RequestResponse
call RunSimulation XmppDeviceControl
call RunSimulation ModBusDeviceControl
call RunSimulation LegalIdentities
