using System;
using System.IO;
using System.Threading.Tasks;
using System.Xml;

namespace TAG.Simulator.ObjectModel.MetaData
{
	/// <summary>
	/// Introduction to model
	/// </summary>
	public class Introduction : SimulationNode
	{
		private string introduction;

		/// <summary>
		/// Description of model
		/// </summary>
		/// <param name="Parent">Parent node</param>
		/// <param name="Model">Model in which the node is defined.</param>
		public Introduction(ISimulationNode Parent, Model Model)
			: base(Parent, Model)
		{
		}

		/// <summary>
		/// Local name of XML element defining contents of class.
		/// </summary>
		public override string LocalName => "Introduction";

		/// <summary>
		/// Description string
		/// </summary>
		public string DescriptionString => this.introduction;

		/// <summary>
		/// Creates a new instance of the node.
		/// </summary>
		/// <param name="Parent">Parent node</param>
		/// <param name="Model">Model in which the node is defined.</param>
		/// <returns>New instance</returns>
		public override ISimulationNode Create(ISimulationNode Parent, Model Model)
		{
			return new Introduction(Parent, Model);
		}

		/// <summary>
		/// Sets properties and attributes of class in accordance with XML definition.
		/// </summary>
		/// <param name="Definition">XML definition</param>
		public override Task FromXml(XmlElement Definition)
		{
			this.introduction = Values.Script.RemoveIndent(Definition.InnerText);

			return Task.CompletedTask;
		}

		/// <summary>
		/// Exports Markdown
		/// </summary>
		/// <param name="Output">Output</param>
		public override Task ExportMarkdown(StreamWriter Output)
		{
			Output.WriteLine(this.introduction);
			Output.WriteLine();

			Output.WriteLine("![Table of Contents](ToC)");
			Output.WriteLine();
			Output.WriteLine("This report has been automatically generated by [ComSim](https://github.com/Trust-Anchor-Group/ComSim)");
			Output.WriteLine("by [Trust Anchor Group](https://trustanchorgroup.com/). The following command-line arguments where used");
			Output.WriteLine("to execute the simulation and generate the report:");
			Output.WriteLine();
			Output.Write("\t");
			Output.WriteLine(this.Model.CommandLine);
			Output.WriteLine();

			return base.ExportMarkdown(Output);
		}

		/// <summary>
		/// Exports XML
		/// </summary>
		/// <param name="Output">Output</param>
		public override Task ExportXml(XmlWriter Output)
		{
			Output.WriteElementString("Introduction", this.introduction);

			return base.ExportXml(Output);
		}
	}
}
